version: '3.9'

services:
  db:
    image: mysql:latest
    ports:
      - 3309:3306
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=pwd
volumes:
  db: {}

