### POST createBoard
POST http://localhost:8080/board
Content-Type: application/json

{
  "title": "title1",
  "content": "content1",
  "userId": "id1"
}

### GET boards
GET http://localhost:8080/board

### GET boardId
GET http://localhost:8080/board/2

### Delete board
DELETE http://localhost:8080/board/1

### Update board
PATCH http://localhost:8080/board/2
Content-Type: application/json

{
  "title": "update title2",
  "content": "update content2"
}

### POST createComment
POST http://localhost:8080/board/2/comment
Content-Type: application/json

{
  "content": "content1",
  "userId": "1"
}

### GEt getComments
GET http://localhost:8080/board/2/comment

### GET getCommnet
GET http://localhost:8080/board/comment/1

### POST createReply
POST http://localhost:8080/comment/1/reply
Content-Type: application/json

{
  "content": "reply1",
  "userId": "userId232"
}

### GET getRepllies
GET http://localhost:8080/comment/1/reply

### DELETE deleteReply
DELETE http://localhost:8080/comment/reply/54

### GET getReply
GET http://localhost:8080/comment/reply/55